[package]
name = "order_book"
version = "0.1.0"
edition = "2024"

[dependencies]
tungstenite= { version = "*" ,features = ["native-tls"]}
serde_json="*"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }

